Prepare Thunder for Drupal 8.6
BurdaMagazinOrg/thunder-distribution pull request #582
Opened 2018-08-02 12:39 UTC by chrfritsch

Make sure these boxes are checked before submitting your pull request - thank you!

- [ ] All coding styles are fulfilled. ([How to check for cs issues?](https://github.com/BurdaMagazinOrg/thunder-dev-tools/blob/master/README.md#code-style-guidelines))
- [ ] All tests are running locally. ([How to run the test?](https://github.com/BurdaMagazinOrg/thunder-distribution/blob/develop/docs/development.md#how-to-run-the-tests))
- [ ] Necessary update hooks are provided.
- [ ] User roles have correct access for new introduced permission.
- [ ] Every thunder module has a README.md in its root. Follow [this guidelines](https://www.drupal.org/node/2181737), but we don't need every topic.
- [ ] Code is covered with well-balanced amount of inline comments.

If you are really awesome, then your feature is covered by additional tests. Well done!

2018-08-08 11:25 UTC, alexpott commented on modules/thunder_taxonomy/thunder_taxonomy.install
> +
I think we need to do something like
`
  // Uninstall the 'content_translation_status' field if needed.
  if ($has_content_translation_status_field) {
    $content_translation_status = $definition_update_manager->getFieldStorageDefinition('content_translation_status', 'taxonomy_term');
    $definition_update_manager->uninstallFieldStorageDefinition($content_translation_status);
  }
`
ala https://www.drupal.org/node/2985366

2018-08-08 11:25 UTC, alexpott commented on modules/thunder_taxonomy/thunder_taxonomy.install
> +function thunder_taxonomy_update_8003() {
We have a problem with taxonomy_update_8601(). Our users will get a message which if they followed the instructions would result in additional unnecessary fields on their taxonomy. See https://www.drupal.org/project/drupal/issues/2991346

2018-08-09 09:17 UTC, alexpott requested changes
Just one thing left from my side. Everything else looks really good.

2018-08-09 09:17 UTC, alexpott commented on thunder.install
> +  \Drupal::state()->set('taxonomy_update_8601_skip_message', 'This update function was skipped, because Thunder provides it\'s own update for the status field on taxonomy terms.');
Here we can be smart and only set this if the taxonomy_update_8601 is in the list of pending updates.

2018-08-09 12:45 UTC, alexpott approved these changes

2018-08-09 12:57 UTC, chrfritsch commented
This is not yet ready. The Drupal\Tests\thunder\Functional\Installer\ThunderInstallerTest is still failing for some reason on php5.6
This test is only executed if "[TEST_UPDATE=true]" is in the commit message.

2018-08-09 21:47 UTC, alexpott commented on composer.json
> +                "The message displayed by taxonomy_update_8601() should be overridable": "https://www.drupal.org/files/issues/2018-08-08/2991346-4.patch"
This made it in so we no longer need it.

2018-08-09 21:47 UTC, alexpott submitted a review, later dismissed
Need to remove the patch

2018-08-10 10:37 UTC, chrfritsch commented
Looks like we have to adjust the update path again
https://www.drupal.org/project/drupal/issues/2991902

2018-08-27 08:43 UTC, chrfritsch commented
I think this is ready now

2018-08-28 13:19 UTC, dbosen approved these changes
So nice!

2018-08-28 14:15 UTC, merged