Issue #3003428 by Insasse, indigoxela, chr.fritsch: Disabled content_moderation breaks Thunder
BurdaMagazinOrg/thunder-distribution pull request #597
Opened 2018-10-04 08:23 UTC by chrfritsch

…moderation breaks Thunder

Make sure these boxes are checked before submitting your pull request - thank you!

- [ ] All coding styles are fulfilled. ([How to check for cs issues?](https://github.com/BurdaMagazinOrg/thunder-dev-tools/blob/master/README.md#code-style-guidelines))
- [ ] All tests are running locally. ([How to run the test?](https://github.com/BurdaMagazinOrg/thunder-distribution/blob/develop/docs/development.md#how-to-run-the-tests))
- [ ] Necessary update hooks are provided.
- [ ] User roles have correct access for new introduced permission.
- [ ] Every thunder module has a README.md in its root. Follow [this guidelines](https://www.drupal.org/node/2181737), but we don't need every topic.
- [ ] Code is covered with well-balanced amount of inline comments.

If you are really awesome, then your feature is covered by additional tests. Well done!

2018-10-08 10:05 UTC, indigoxela approved these changes
Several users on drupal.org confirm that this commit fixes the errors and makes Thunder usable without module content_moderation again.

See https://www.drupal.org/project/thunder/issues/3003428 for details.

2018-10-09 07:20 UTC, dbosen requested changes

2018-10-09 07:20 UTC, dbosen commented on thunder.profile
> +    if (!Role::load('restricted_editor')) {
Why not try / catching the possible exceptions from $configReverter->import() instead?

2018-10-09 12:27 UTC, dbosen approved these changes

2018-10-09 13:22 UTC, mtodor approved these changes
Looks good

2018-10-09 13:29 UTC, merged