Issue #3044358: Update travis to PHP 7.3
BurdaMagazinOrg/thunder-distribution pull request #638
Opened 2019-01-07 13:23 UTC by chrfritsch

Make sure these boxes are checked before submitting your pull request - thank you!

- [ ] All coding styles are fulfilled. ([How to check for cs issues?](https://github.com/BurdaMagazinOrg/thunder-dev-tools/blob/master/README.md#code-style-guidelines))
- [ ] All tests are running locally. ([How to run the test?](https://github.com/BurdaMagazinOrg/thunder-distribution/blob/develop/docs/development.md#how-to-run-the-tests))
- [ ] Necessary update hooks are provided.
- [ ] User roles have correct access for new introduced permission.
- [ ] Every thunder module has a README.md in its root. Follow [this guidelines](https://www.drupal.org/node/2181737), but we don't need every topic.
- [ ] Code is covered with well-balanced amount of inline comments.

If you are really awesome, then your feature is covered by additional tests. Well done!

2019-03-29 10:00 UTC, chrfritsch commented
Mystery solved:

```
handleUpload uses coninue in a switch: https://cgit.drupalcode.org/dropzonejs/tree/src/UploadHandler.php
Triggering a PHP error:

PHP 7.3 Bug: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"

```

2019-04-02 10:38 UTC, alexpott submitted a review, later dismissed
Looks good. I wonder when we're going to drop PHP 5 support. There is update support for PHP5 in 8.7.x but you can't install on PHP 5 (for what it is worth).

2019-04-16 05:25 UTC, dbosen requested changes

2019-04-16 05:25 UTC, dbosen commented on docs/development.md
> +All Thunder pull requests are execute on [Travis CI](https://travis-ci.org/BurdaMagazinOrg/thunder-distribution). On every pull request tests will be executed (or when new commits are pushed into pul
This comment is not correct anymore, we do not test against 5.6 for a while now.

2019-04-16 05:26 UTC, dbosen commented
> 
> 
> Looks good. I wonder when we're going to drop PHP 5 support. There is update support for PHP5 in 8.7.x but you can't install on PHP 5 (for what it is worth

2019-04-16 07:43 UTC, dbosen approved these changes

2019-04-16 08:41 UTC, merged