Update paragraphs to 1.7
BurdaMagazinOrg/thunder-distribution pull request #677
Opened 2019-03-21 10:16 UTC by chrfritsch

Make sure these boxes are checked before submitting your pull request - thank you!

- [ ] All coding styles are fulfilled. ([How to check for cs issues?](https://github.com/BurdaMagazinOrg/thunder-dev-tools/blob/master/README.md#code-style-guidelines))
- [ ] All tests are running locally. ([How to run the test?](https://github.com/BurdaMagazinOrg/thunder-distribution/blob/develop/docs/development.md#how-to-run-the-tests))
- [ ] Necessary update hooks are provided.
- [ ] User roles have correct access for new introduced permission.
- [ ] Every thunder module has a README.md in its root. Follow [this guidelines](https://www.drupal.org/node/2181737), but we don't need every topic.
- [ ] Code is covered with well-balanced amount of inline comments.

If you are really awesome, then your feature is covered by additional tests. Well done!

2019-03-21 13:42 UTC, dbosen commented on composer.json
> +        "drupal/paragraphs": "^1.0",
needs to be ^1.7

2019-03-21 13:42 UTC, dbosen submitted a review, later dismissed

2019-03-21 13:42 UTC, dbosen commented on composer.json
> -                "Support of add above functionality in Thunder": "https://www.drupal.org/files/issues/2018-09-28/2977454_7.patch"
Yes!

2019-03-26 10:41 UTC, chrfritsch commented on composer.json
> +        "drupal/paragraphs": "^1.0",
Done

2019-08-21 07:23 UTC, dbosen requested changes
see comment

2019-08-21 07:23 UTC, dbosen commented on thunder.install
> +  if ($phase !== 'update') {
maybe we can use drupal_valid_test_ua() here and crap the patch for tests.

2019-08-21 12:12 UTC, dbosen approved these changes

2019-08-21 12:14 UTC, merged