Issue #3059036: Move facebook integration to its own module
BurdaMagazinOrg/thunder-distribution pull request #705
Opened 2019-06-03 12:16 UTC by ol0lll

Make sure these boxes are checked before submitting your pull request - thank you!

- [ ] All coding styles are fulfilled. ([How to check for cs issues?](https://github.com/BurdaMagazinOrg/thunder-dev-tools/blob/master/README.md#code-style-guidelines))
- [ ] All tests are running locally. ([How to run the test?](https://github.com/BurdaMagazinOrg/thunder-distribution/blob/develop/docs/development.md#how-to-run-the-tests))
- [ ] Necessary update hooks are provided.
- [ ] User roles have correct access for new introduced permission.
- [ ] Every thunder module has a README.md in its root. Follow [this guidelines](https://www.drupal.org/node/2181737), but we don't need every topic.
- [ ] Code is covered with well-balanced amount of inline comments.

If you are really awesome, then your feature is covered by additional tests. Well done!

2019-10-14 11:34 UTC, ol0lll commented
Two fixes are needed in fb_instant_articles:

https://github.com/BurdaMagazinOrg/module-fb_instant_articles/pull/140
https://github.com/BurdaMagazinOrg/module-fb_instant_articles/pull/141

2019-10-24 13:01 UTC, dbosen requested changes

2019-10-24 13:01 UTC, dbosen commented on composer.json
> +        "drupal/thunder_fia": "2.x-dev",
we need to require "^1.0 || 2.x-dev" or "^1.0 || ^ 2.0"  of tags are available

2020-02-03 15:48 UTC, ol0lll commented
Will not be done for thunder 2.x, closing in favour of thunder/thunder-distribution#151

2020-02-03 15:48 UTC, closed without merging