Issue #3059646: Consider upgrading field_group module
BurdaMagazinOrg/thunder-distribution pull request #711
Opened 2019-06-27 11:19 UTC by ol0lll

Make sure these boxes are checked before submitting your pull request - thank you!

- [ ] All coding styles are fulfilled. ([How to check for cs issues?](https://github.com/BurdaMagazinOrg/thunder-dev-tools/blob/master/README.md#code-style-guidelines))
- [ ] All tests are running locally. ([How to run the test?](https://github.com/BurdaMagazinOrg/thunder-distribution/blob/develop/docs/development.md#how-to-run-the-tests))
- [ ] Necessary update hooks are provided.
- [ ] User roles have correct access for new introduced permission.
- [ ] Every thunder module has a README.md in its root. Follow [this guidelines](https://www.drupal.org/node/2181737), but we don't need every topic.
- [ ] Code is covered with well-balanced amount of inline comments.

If you are really awesome, then your feature is covered by additional tests. Well done!

2019-06-27 11:19 UTC, ol0lll commented
The field_group module provides update hook setting the 'region' key for each field_group.

2019-07-01 14:53 UTC, ol0lll commented
* Missing state handling: https://www.drupal.org/project/field_group/issues/3013395

2019-07-01 15:21 UTC, dbosen requested changes
The inline form display of image media entity is broken now. Can be seen, when you open an image entity paragraph for editing, all the input fields are differently layouted than before.
Could also be the case on other form displays, but I did not find any.

2019-07-03 08:30 UTC, ol0lll commented
Patch from https://www.drupal.org/i/2907094 fixes field_groups which are directly in paragraphs, a use case we don't implement.
Patch from https://www.drupal.org/i/2986704 fixes field_groups in IEF - applied that.

2019-07-03 12:34 UTC, chrfritsch requested changes

2019-07-03 12:34 UTC, chrfritsch commented on composer.json
> +        "drupal/field_group": "^3.0",
We have to fix the version.

2019-07-03 12:34 UTC, chrfritsch commented on drupal-org.make
> +projects[field_group][version] = 3
We have to fix the version.

2019-07-03 12:34 UTC, chrfritsch commented on drupal-org.make
> +projects[field_group][version] = 3
Field group and paragraphs patch are missing

2019-07-03 13:19 UTC, chrfritsch submitted a review, later dismissed
Looks good to me

2019-08-06 07:38 UTC, chrfritsch commented
Let's wait for the new paragraphs release now. Then we can get rid of the additional paragraphs patch

2019-08-22 12:25 UTC, merged